# Configuration for Yasb (Yet Another Status Bar)
# Author: @denBot
# Last updated: 21/08/2023

# General Bar Configuration Notes:
#   - All bars must be defined in within the `bars` section
#   - Each bar configuration should be defined using a name, e.g. 'Laptop-bar', 'my-awesome-bar', etc.
#   - Default bar options can be found at: https://github.com/denBot/yasb/blob/main/src/core/validation/bar.py#L1-L10

# General Widget Configuration Notes:
#   - ALL configured widgets must be defined in within the `widgets` section of this config file
#   - Each widget configuration should be allocated a unique name, e.g. 'my-widget', 'my-custom-clock', etc.
#      >  This makes it easier for you to keep track of your configured widgets and add them to your bar(s)
#   - Each widget should specify a widget `type` - this points to the python class of the widget you are configuring
#      > For example: type: "yasb.clock.ClockWidget"
#   - Each widget supports mouse event callback functionality (left, middle, right click).
#      > The callbacks "do_nothing" and "exec" can be used across any widget which allows them.
#      > "exec" allows you to run programs from the command-line, where each argument is separated by a space
#      > "do_nothing" allows you to override default mouse events to do nothing
#      > "toggle_label" *some widgets* allow you to toggle between two label formats
#   - Example callbacks:
#      on_left: "exec wt.exe"  --  run the windows terminal when the widget is left-clicked
#      on_middle: "do_nothing" -- overrides default widget middle-click behaviour to do nothing
#      on_right: "exec cmd /c Taskmg" --  open the task manager when the widget is right-clicked


watch_stylesheet: true
watch_config: true

bars:
  Laptop-bar:
    enabled: true
    screens: ['\\.\DISPLAY1']
    class_name: "Laptop-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: true
      dark: false
    window_flags:
      always_on_top: true
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:   ["open_startmenu", "komorebi_workspaces", "komorebi_active_layout", "ip_info"]
      center: ["clock", "weather"]
      right:  [ "dropdown_menu", "terminal_button", "explorer_button",  "volume", "cpu", "memory", "wifi", "battery"]

  monitor-bar:
    enabled: true
    screens: ['HP E34m G4']
    class_name: "monitor-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: False
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:   ["komorebi_workspaces", "komorebi_active_layout", "active_window"]
      center: ["clock", "weather"]
      right:  ["terminal_button", "explorer_button", "ip_info", "volume", "disk", "cpu", "memory", "wifi", "battery"]

widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][name]}"
      label_alt: "exe='{win[process][name]}' display='{win[monitor_info][device]}'"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: false

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      time_remaining_natural: true 
      label: "{icon}"
      label_alt: "{percent}%"
      update_interval: 1000
      charging_options:
        icon_format: "{charging_icon} {icon}"
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\uf0e7"
        icon_critical: "\udb80\udc83"
        icon_low: "\udb80\udc7a"
        icon_medium: "\udb80\udc7c"
        icon_high: "\udb80\udc80"
        icon_full: "\udb80\udc79"


  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "{%H:%M:%S %Z}"
        label_alt: "{%d-%m-%y %H:%M:%S %Z}"
        timezones: ["Europe/Amsterdam", "America/New_York"]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\ue266 CPU:{info[percent][total]}%"
      label_alt: "CPU:{info[histograms][cpu_percent]}"
      update_interval: 1000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2582' # 10%
        - '\u2583' # 20%
        - '\u2584' # 30%
        - '\u2585' # 40%
        - '\u2586' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 20

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "\ue266 RAM:{virtual_mem_percent}%"
        label_alt: "\ue266 RAM:{virtual_mem_free}"
        update_interval: 2000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{index}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: true

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "[\\\\]"
        columns: "[||]"
        rows: "[==]"
        vertical_stack: "[V]="
        horizontal_stack: "[H]="
        ultrawide_vertical_stack: "||="
        monocle: "[M]"
        maximised: "[X]"
        floating: "><>"
        paused: "[P]"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
        label: "{wifi_icon}"
        label_alt: "{wifi_icon} {wifi_name}"
        update_interval: 5000
        wifi_icons:
          - "<span style=\"color: #d15142\">\udb82\udd2e</span>"  # 0% strength (no wifi)
          - "<span style=\"color: #df8a45\">\udb82\udd1f</span>"  # 1-25% strength
          - "<span style=\"color: #e2b345\">\udb82\udd22</span>"  # 26-50% strength
          - "<span style=\"color: #b7b85a\">\udb82\udd25</span>"  # 51-75% strength
          - "<span style=\"color: #5f924d\">\udb82\udd28</span>"  # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  traffic:
    type: "yasb.traffic.TrafficWidget"
  options:
      label: "\ueb01 \ueab4 {download_speed}"
      label_alt: "\ueb01 \ueab7 {download_speed} | \ueab4 {upload_speed} |"
      update_interval: 1000 # Update interval should be a multiple of 1000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  # Some custom widgets

  explorer_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue6ad"
      label_alt: "Explorer"
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: "toggle_label"
  
  terminal_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf4b5"
      label_alt: "\uf4b5"
      class_name: "terminal-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec wt.exe"


  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udb82\ude60 {data[ip]}"
      label_alt: "\udb82\ude60 [Hidden]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                        # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2  {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2 {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe  wttr.in/Amsterdam?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"
  
  open_startmenu:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "Start Menu"
      class_name: "start_widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: exec cscript /B C:\Users\Pim\Desktop\prive\config_files\openstart.vbs

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
        label: "\uf028 {volume[percent]}"
        label_alt: "\uf028 {volume[percent]}"
        update_interval: 500
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "\udb80\udeca {volume_label}{space[used][percent]:.1f}%"
        label_alt: "\udb80\udeca {volume_label}{space[used][gb]:.1f}GB / {space[total][gb]:.1f}GB"
        volume_label: "C:"
        update_interval: 60000
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  dropdown_menu:
    type: "yasb.dropdown.DropdownWidget"
    options:
      items:
        "CPU Monitor": "cpu"
        "Memory Monitor": "memory"
        "Volume Control": "volume"
      update_interval: 5000
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"